CELERY_SENDER_IMPORTS = ('apps.sender.tasks',)
CELERY_SENDER_ACCEPT_CONTENT = ['json']
CELERY_SENDER_TASK_SERIALIZER = 'json'
CELERY_SENDER_BROKER_URL = os.environ['CELERY_SENDER_BROKER_URL']  # type: ignore
CELERY_SENDER_TIMEZONE = 'UTC'
CELERY_SENDER_CACHE_BACKEND = 'default'
